// mapping between a country on the map and the bm data
const iso_a3 = {
  'Argentina': 'ARG',
  'Australia': 'AUS',
  'Azerbaijan': 'AZE',
  'Bahrain': 'BHR',
  'Brazil': 'BRA',
  'Britain': 'GBR',
  'Canada': 'CAN',
  'Chile': 'CHL',
  'China': 'CHN',
  'Colombia': 'COL',
  'Costa Rica': 'CRI',
  'Croatia': 'HRV',
  'Czech Republic': 'CZE',
  'Denmark': 'DNK',
  'Egypt': 'EGY',
  'Euro area': 'EUZ',
  'Guatemala': 'GTM',
  'Honduras': 'HND',
  'Hong Kong': 'HKG',
  'Hungary': 'HUN',
  'India': 'IND',
  'Indonesia': 'IDN',
  'Israel': 'ISR',
  'Japan': 'JPN',
  'Jordan': 'JOR',
  'Kuwait': 'KWT',
  'Lebanon': 'LBN',
  'Malaysia': 'MYS',
  'Mexico': 'MEX',
  'Moldova': 'MDA',
  'New Zealand': 'NZL',
  'Nicaragua': 'NIC',
  'Norway': 'NOR',
  'Oman': 'OMN',
  'Pakistan': 'PAK',
  'Peru': 'PER',
  'Philippines': 'PHL',
  'Poland': 'POL',
  'Qatar': 'QAT',
  'Romania': 'ROU',
  'Russia': 'RUS',
  'Saudi Arabia': 'SAU',
  'Singapore': 'SGP',
  'South Africa': 'ZAF',
  'South Korea': 'KOR',
  'Sri Lanka': 'LKA',
  'Sweden': 'SWE',
  'Switzerland': 'CHE',
  'Taiwan': 'TWN',
  'Thailand': 'THA',
  'Turkey': 'TUR',
  'Ukraine': 'UKR',
  'United Arab Emirates': 'ARE',
  'United Kingdom': 'GBR',
  'United States': 'USA',
  'United States of America': 'USA',
  'Uruguay': 'URY',
  'Venezuela': 'VEN',
  'Vietnam': 'VNM'
};

const euroZone = [
  'Austria',   'Belgium',    'Croatia',  'Republic of Cyprus',
  'Estonia',   'Finland',    'France',   'Germany',
  'Greece',    'Ireland',    'Italy',    'Latvia',
  'Lithuania', 'Luxembourg', 'Malta',    'Netherlands',
  'Portugal',  'Slovakia',   'Slovenia', 'Spain',
  'Euro area',
];

const bigMacMap = {
  __proto__: iso_a3,
  ...Object.fromEntries(euroZone.map((x) => [x, 'EUZ'])),
};

const cpiMap = {
  'Argentina': 'ARG',
  'Australia': 'AUS',
  'Canada': 'CAN',
  'Britain': 'GBR',
  'Japan': 'JPN',
  'New Zealand': 'NZL',
  'Russia': 'RUS',
  'United States of America': 'USA',
  'Switzerland': 'CHE',
  ...Object.fromEntries(euroZone.map((x) => [x, 'EUR'])),
};

const worldBankMap = {
  'United States of America': 'United States',
  'United Kingdom': 'Britain',
  'Dem. Rep. Congo': 'Congo, Dem. Rep.',
  'Central African Rep.': 'Central African Republic',
  'North Korea': 'Korea, Rep.',
  'South Korea': 'Korea, Rep.',
  'Egypt': 'Egypt, Arab Rep.',
  'Venezuela': 'Venezuela, RB',
  'Russia': 'Russian Federation',
};
